/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorldLeagueRouteImport } from './routes/_authenticated/world-league'
import { Route as AuthenticatedWorldCupRouteImport } from './routes/_authenticated/world-cup'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedLineupRouteImport } from './routes/_authenticated/lineup'
import { Route as AuthenticatedLeagueRouteImport } from './routes/_authenticated/league'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedDevRouteImport } from './routes/_authenticated/dev'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCupRouteImport } from './routes/_authenticated/cup'
import { Route as AuthenticatedCareerRouteImport } from './routes/_authenticated/career'
import { Route as AuthenticatedBuildingsRouteImport } from './routes/_authenticated/buildings'
import { Route as AuthenticatedMatchIdRouteImport } from './routes/_authenticated/match.$id'
import { Route as AuthenticatedCreaturesIdRouteImport } from './routes/_authenticated/creatures.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorldLeagueRoute =
  AuthenticatedWorldLeagueRouteImport.update({
    id: '/world-league',
    path: '/world-league',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorldCupRoute = AuthenticatedWorldCupRouteImport.update({
  id: '/world-cup',
  path: '/world-cup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLineupRoute = AuthenticatedLineupRouteImport.update({
  id: '/lineup',
  path: '/lineup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeagueRoute = AuthenticatedLeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevRoute = AuthenticatedDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCupRoute = AuthenticatedCupRouteImport.update({
  id: '/cup',
  path: '/cup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareerRoute = AuthenticatedCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuildingsRoute = AuthenticatedBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchIdRoute = AuthenticatedMatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreaturesIdRoute =
  AuthenticatedCreaturesIdRouteImport.update({
    id: '/creatures/$id',
    path: '/creatures/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/career': typeof AuthenticatedCareerRoute
  '/cup': typeof AuthenticatedCupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dev': typeof AuthenticatedDevRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/league': typeof AuthenticatedLeagueRoute
  '/lineup': typeof AuthenticatedLineupRoute
  '/market': typeof AuthenticatedMarketRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/shop': typeof AuthenticatedShopRoute
  '/world-cup': typeof AuthenticatedWorldCupRoute
  '/world-league': typeof AuthenticatedWorldLeagueRoute
  '/creatures/$id': typeof AuthenticatedCreaturesIdRoute
  '/match/$id': typeof AuthenticatedMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/career': typeof AuthenticatedCareerRoute
  '/cup': typeof AuthenticatedCupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dev': typeof AuthenticatedDevRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/league': typeof AuthenticatedLeagueRoute
  '/lineup': typeof AuthenticatedLineupRoute
  '/market': typeof AuthenticatedMarketRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/shop': typeof AuthenticatedShopRoute
  '/world-cup': typeof AuthenticatedWorldCupRoute
  '/world-league': typeof AuthenticatedWorldLeagueRoute
  '/creatures/$id': typeof AuthenticatedCreaturesIdRoute
  '/match/$id': typeof AuthenticatedMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/buildings': typeof AuthenticatedBuildingsRoute
  '/_authenticated/career': typeof AuthenticatedCareerRoute
  '/_authenticated/cup': typeof AuthenticatedCupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dev': typeof AuthenticatedDevRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/league': typeof AuthenticatedLeagueRoute
  '/_authenticated/lineup': typeof AuthenticatedLineupRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/world-cup': typeof AuthenticatedWorldCupRoute
  '/_authenticated/world-league': typeof AuthenticatedWorldLeagueRoute
  '/_authenticated/creatures/$id': typeof AuthenticatedCreaturesIdRoute
  '/_authenticated/match/$id': typeof AuthenticatedMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buildings'
    | '/career'
    | '/cup'
    | '/dashboard'
    | '/dev'
    | '/finances'
    | '/league'
    | '/lineup'
    | '/market'
    | '/messages'
    | '/onboarding'
    | '/ranking'
    | '/roster'
    | '/shop'
    | '/world-cup'
    | '/world-league'
    | '/creatures/$id'
    | '/match/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buildings'
    | '/career'
    | '/cup'
    | '/dashboard'
    | '/dev'
    | '/finances'
    | '/league'
    | '/lineup'
    | '/market'
    | '/messages'
    | '/onboarding'
    | '/ranking'
    | '/roster'
    | '/shop'
    | '/world-cup'
    | '/world-league'
    | '/creatures/$id'
    | '/match/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/buildings'
    | '/_authenticated/career'
    | '/_authenticated/cup'
    | '/_authenticated/dashboard'
    | '/_authenticated/dev'
    | '/_authenticated/finances'
    | '/_authenticated/league'
    | '/_authenticated/lineup'
    | '/_authenticated/market'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/_authenticated/ranking'
    | '/_authenticated/roster'
    | '/_authenticated/shop'
    | '/_authenticated/world-cup'
    | '/_authenticated/world-league'
    | '/_authenticated/creatures/$id'
    | '/_authenticated/match/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/world-league': {
      id: '/_authenticated/world-league'
      path: '/world-league'
      fullPath: '/world-league'
      preLoaderRoute: typeof AuthenticatedWorldLeagueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/world-cup': {
      id: '/_authenticated/world-cup'
      path: '/world-cup'
      fullPath: '/world-cup'
      preLoaderRoute: typeof AuthenticatedWorldCupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lineup': {
      id: '/_authenticated/lineup'
      path: '/lineup'
      fullPath: '/lineup'
      preLoaderRoute: typeof AuthenticatedLineupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league': {
      id: '/_authenticated/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof AuthenticatedLeagueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev': {
      id: '/_authenticated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthenticatedDevRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cup': {
      id: '/_authenticated/cup'
      path: '/cup'
      fullPath: '/cup'
      preLoaderRoute: typeof AuthenticatedCupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career': {
      id: '/_authenticated/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof AuthenticatedCareerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buildings': {
      id: '/_authenticated/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof AuthenticatedBuildingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match/$id': {
      id: '/_authenticated/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof AuthenticatedMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creatures/$id': {
      id: '/_authenticated/creatures/$id'
      path: '/creatures/$id'
      fullPath: '/creatures/$id'
      preLoaderRoute: typeof AuthenticatedCreaturesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuildingsRoute: typeof AuthenticatedBuildingsRoute
  AuthenticatedCareerRoute: typeof AuthenticatedCareerRoute
  AuthenticatedCupRoute: typeof AuthenticatedCupRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevRoute: typeof AuthenticatedDevRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedLeagueRoute: typeof AuthenticatedLeagueRoute
  AuthenticatedLineupRoute: typeof AuthenticatedLineupRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedWorldCupRoute: typeof AuthenticatedWorldCupRoute
  AuthenticatedWorldLeagueRoute: typeof AuthenticatedWorldLeagueRoute
  AuthenticatedCreaturesIdRoute: typeof AuthenticatedCreaturesIdRoute
  AuthenticatedMatchIdRoute: typeof AuthenticatedMatchIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuildingsRoute: AuthenticatedBuildingsRoute,
  AuthenticatedCareerRoute: AuthenticatedCareerRoute,
  AuthenticatedCupRoute: AuthenticatedCupRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevRoute: AuthenticatedDevRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedLeagueRoute: AuthenticatedLeagueRoute,
  AuthenticatedLineupRoute: AuthenticatedLineupRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedWorldCupRoute: AuthenticatedWorldCupRoute,
  AuthenticatedWorldLeagueRoute: AuthenticatedWorldLeagueRoute,
  AuthenticatedCreaturesIdRoute: AuthenticatedCreaturesIdRoute,
  AuthenticatedMatchIdRoute: AuthenticatedMatchIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
