// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getCookie, getRequest } from '@tanstack/react-start/server'
import { GAME_SESSION_COOKIE } from './session.functions'
import { getDirectSession } from '@/lib/direct-session.server'

// Browser-safe project credentials. These are intentionally limited to the
// publishable key and are protected by the database RLS policies.
const PUBLIC_SUPABASE_URL = 'https://gwqvninbrmrsabuseqbx.supabase.co';
const PUBLIC_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_ycTtamLVwKvO3G89F5dAfw_W6ozxpo9';



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next, context }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL || PUBLIC_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY || PUBLIC_SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const contextToken = (context as { supabaseAccessToken?: unknown } | undefined)
      ?.supabaseAccessToken;
    const transportedToken = typeof contextToken === 'string' ? contextToken : null;
    const sessionCookieToken = getCookie(GAME_SESSION_COOKIE) ?? null;
    const forwardedToken = request.headers.get('x-supabase-access-token');
    const authHeader = request.headers.get('authorization');

    if (!sessionCookieToken && !transportedToken && !forwardedToken && !authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!sessionCookieToken && !transportedToken && !forwardedToken && !authHeader?.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const bearerToken = authHeader?.startsWith('Bearer ')
      ? authHeader.slice('Bearer '.length)
      : null;
    // A sessão atual enviada pelo cliente sempre vence. O cookie HttpOnly é
    // somente fallback, pois uma publicação antiga do Lovable pode conservá-lo
    // depois de o Supabase já ter renovado o JWT no navegador.
    const token = transportedToken || forwardedToken || bearerToken || sessionCookieToken;
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    // Todas as funções do jogo, inclusive as que recebem o JWT no corpo,
    // passam pelo mesmo verificador. Isso impede divergência entre Mercado,
    // Construções, Liga, Finanças e as demais páginas protegidas.
    const { supabase, userId } = await getDirectSession(token);

    return next({
      context: {
        supabase,
        userId,
      },
    });
  },
);
