// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'
import { syncServerSession } from './session.functions'

let syncingSession = false
let lastSyncedToken: string | null = null
let lastSyncedAt = 0

async function ensureServerSession(token: string) {
  const isFresh =
    token === lastSyncedToken && Date.now() - lastSyncedAt < 10 * 60 * 1000
  if (isFresh || syncingSession) return

  syncingSession = true
  try {
    await syncServerSession({ data: { accessToken: token } })
    lastSyncedToken = token
    lastSyncedAt = Date.now()
  } finally {
    syncingSession = false
  }
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token

    // A própria função de sincronização também passa pelo middleware global.
    // O bloqueio evita recursão e deixa essa chamada pública chegar ao servidor.
    if (token && !syncingSession) {
      await ensureServerSession(token)
    }

    return next({
      // Transporte oficial das Server Functions: segue no corpo da chamada e
      // não pode ser substituído pelo proxy de hospedagem.
      sendContext: token ? { supabaseAccessToken: token } : {},
      // Lovable pode usar/substituir `Authorization` no proxy das Server
      // Functions. O cabeçalho próprio preserva a sessão real do jogo.
      headers: token
        ? {
            Authorization: `Bearer ${token}`,
            'x-supabase-access-token': token,
          }
        : {},
    })
  },
)
