// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'
import { syncServerSession } from './session.functions'

let sessionSyncPromise: Promise<void> | null = null
let lastSyncedToken: string | null = null
let lastSyncedAt = 0

export async function ensureServerSession(token: string) {
  const isFresh =
    token === lastSyncedToken && Date.now() - lastSyncedAt < 10 * 60 * 1000
  if (isFresh) return

  // Mais de uma tela pode iniciar ao mesmo tempo. Todas precisam aguardar a
  // mesma sincronização; retornar imediatamente aqui criava uma corrida em que
  // o dashboard consultava o servidor antes de o cookie existir.
  if (sessionSyncPromise) {
    await sessionSyncPromise
    if (token === lastSyncedToken) return
  }

  const sync = (async () => {
    await syncServerSession({ data: { accessToken: token } })
    lastSyncedToken = token
    lastSyncedAt = Date.now()
  })()
  sessionSyncPromise = sync
  try {
    await sync
  } finally {
    if (sessionSyncPromise === sync) sessionSyncPromise = null
  }
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token

    // A própria função de sincronização também passa pelo middleware global.
    // O bloqueio evita recursão e deixa essa chamada pública chegar ao servidor.
    if (token && !sessionSyncPromise) {
      // O cookie é apenas compatibilidade para funções antigas. Uma falha do
      // host ao persistir esse cookie nunca pode impedir a função solicitada de
      // receber o token pelo contexto/corpo da chamada.
      try {
        await ensureServerSession(token)
      } catch (error) {
        console.warn('[Supabase] Não foi possível sincronizar o cookie de compatibilidade.', error)
      }
    }

    return next({
      // Transporte oficial das Server Functions: segue no corpo da chamada e
      // não pode ser substituído pelo proxy de hospedagem.
      sendContext: token ? { supabaseAccessToken: token } : {},
      // Lovable pode usar/substituir `Authorization` no proxy das Server
      // Functions. O cabeçalho próprio preserva a sessão real do jogo.
      headers: token
        ? {
            Authorization: `Bearer ${token}`,
            'x-supabase-access-token': token,
          }
        : {},
    })
  },
)
