// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getCookie, getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { GAME_SESSION_COOKIE } from './session.functions'

// Browser-safe project credentials. These are intentionally limited to the
// publishable key and are protected by the database RLS policies.
const PUBLIC_SUPABASE_URL = 'https://gwqvninbrmrsabuseqbx.supabase.co';
const PUBLIC_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_ycTtamLVwKvO3G89F5dAfw_W6ozxpo9';



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next, context }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL || PUBLIC_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY || PUBLIC_SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const contextToken = (context as { supabaseAccessToken?: unknown } | undefined)
      ?.supabaseAccessToken;
    const transportedToken = typeof contextToken === 'string' ? contextToken : null;
    const sessionCookieToken = getCookie(GAME_SESSION_COOKIE) ?? null;
    const forwardedToken = request.headers.get('x-supabase-access-token');
    const authHeader = request.headers.get('authorization');

    if (!sessionCookieToken && !transportedToken && !forwardedToken && !authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!sessionCookieToken && !transportedToken && !forwardedToken && !authHeader!.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    // O contexto serializado é o transporte oficial do TanStack Start. Os
    // cabeçalhos permanecem como compatibilidade para desenvolvimento local.
    const token = sessionCookieToken || transportedToken || forwardedToken || authHeader!.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    // `getClaims` depends on local/JWKS claim verification and can reject an
    // otherwise valid browser session when a hosted server function is
    // invoked through Lovable's proxy. `getUser(token)` asks Supabase Auth to
    // verify the token directly, which is the authoritative check here.
    const { data, error } = await supabase.auth.getUser(token);
    if (error || !data?.user) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.user.id) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.user.id,
        claims: data.user,
      },
    });
  },
);
