// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getCookie, getRequest } from '@tanstack/react-start/server'
import { GAME_SESSION_COOKIE } from './session.functions'
import { getDirectSession } from '@/lib/direct-session.server'

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next, context }) => {
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const contextToken = (context as { supabaseAccessToken?: unknown } | undefined)
      ?.supabaseAccessToken;
    const transportedToken = typeof contextToken === 'string' ? contextToken : null;
    const sessionCookieToken = getCookie(GAME_SESSION_COOKIE) ?? null;
    const forwardedToken = request.headers.get('x-supabase-access-token');
    const authHeader = request.headers.get('authorization');

    if (!sessionCookieToken && !transportedToken && !forwardedToken && !authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!sessionCookieToken && !transportedToken && !forwardedToken && !authHeader?.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const bearerToken = authHeader?.startsWith('Bearer ')
      ? authHeader.slice('Bearer '.length)
      : null;
    // A sessão atual enviada pelo cliente sempre vence. O cookie HttpOnly é
    // somente fallback, pois uma publicação antiga do Lovable pode conservá-lo
    // depois de o Supabase já ter renovado o JWT no navegador.
    const token = transportedToken || forwardedToken || bearerToken || sessionCookieToken;
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    // Todas as funções do jogo, inclusive as que recebem o JWT no corpo,
    // passam pelo mesmo verificador. Isso impede divergência entre Mercado,
    // Construções, Liga, Finanças e as demais páginas protegidas.
    const { supabase, userId } = await getDirectSession(token);

    return next({
      context: {
        supabase,
        userId,
      },
    });
  },
);
