// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token

    return next({
      // Transporte oficial das Server Functions: segue no corpo da chamada e
      // não pode ser substituído pelo proxy de hospedagem.
      sendContext: token ? { supabaseAccessToken: token } : {},
      // Lovable pode usar/substituir `Authorization` no proxy das Server
      // Functions. O cabeçalho próprio preserva a sessão real do jogo.
      headers: token
        ? {
            Authorization: `Bearer ${token}`,
            'x-supabase-access-token': token,
          }
        : {},
    })
  },
)
