// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// This is the browser-safe Supabase configuration for Monster Club Manager.
// The publishable key is intentionally public and protected by Supabase RLS;
// it is not a service-role or secret key. Keeping this fallback prevents a
// missing hosting environment variable from leaving the whole game stuck on
// the initial loading screen.
const PUBLIC_SUPABASE_URL = 'https://gwqvninbrmrsabuseqbx.supabase.co';
const PUBLIC_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_ycTtamLVwKvO3G89F5dAfw_W6ozxpo9';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || PUBLIC_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    PUBLIC_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, _supabase);
  },
});

let sessionRefreshPromise: Promise<string> | null = null;

function sessionNeedsRefresh(expiresAt?: number | null) {
  if (!expiresAt) return true;
  return expiresAt * 1000 <= Date.now() + 90_000;
}

/**
 * Entrega um JWT realmente utilizavel pelas funcoes do jogo.
 *
 * `getSession()` pode devolver por alguns instantes um token prestes a vencer.
 * Isso era suficiente para liberar a tela, mas o Auth o recusava quando o
 * jogador confirmava o time ou iniciava uma partida. A renovacao fica
 * centralizada e deduplicada para todas as telas compartilharem a mesma sessao.
 */
export async function getValidAccessToken(options?: { forceRefresh?: boolean }) {
  const { data, error } = await supabase.auth.getSession();
  if (error) throw error;

  const session = data.session;
  const shouldRefresh = options?.forceRefresh || !session || sessionNeedsRefresh(session.expires_at);
  if (!shouldRefresh && session.access_token) return session.access_token;

  if (!sessionRefreshPromise) {
    sessionRefreshPromise = supabase.auth.refreshSession()
      .then(({ data: refreshed, error: refreshError }) => {
        if (refreshError) throw refreshError;
        if (!refreshed.session?.access_token) {
          throw new Error('Sua sessao expirou. Entre novamente.');
        }
        return refreshed.session.access_token;
      })
      .finally(() => {
        sessionRefreshPromise = null;
      });
  }

  return sessionRefreshPromise;
}

export function isExpiredSessionError(error: unknown) {
  const message = error instanceof Error ? error.message : String(error ?? '');
  return /sess[aã]o expirou|invalid token|jwt expired|unauthorized/i.test(message);
}

/** Executa uma acao autenticada e, se o servidor rejeitar o JWT, renova uma vez. */
export async function withValidAccessToken<T>(action: (accessToken: string) => Promise<T>) {
  try {
    return await action(await getValidAccessToken());
  } catch (error) {
    if (!isExpiredSessionError(error)) throw error;
    return action(await getValidAccessToken({ forceRefresh: true }));
  }
}

let authTransportInstalled = false;
let currentAccessToken: string | null = null;

/**
 * Instala o transporte da sessao antes que qualquer rota protegida carregue.
 *
 * O Lovable pode manter um cookie antigo no proxy. Por isso toda chamada a uma
 * Server Function do proprio jogo recebe o JWT atual do Supabase diretamente
 * no cabecalho. A instalacao acontece neste modulo (importado pelas rotas), e
 * nao em um useEffect tardio do layout.
 */
export function installServerFunctionAuthTransport() {
  if (typeof window === 'undefined' || authTransportInstalled) return;
  authTransportInstalled = true;

  const originalFetch = window.fetch.bind(window);
  const refreshToken = async () => {
    try {
      currentAccessToken = await getValidAccessToken();
    } catch {
      currentAccessToken = null;
    }
    return currentAccessToken;
  };

  void refreshToken();
  supabase.auth.onAuthStateChange((_event, session) => {
    currentAccessToken = session?.access_token ?? null;
  });

  window.fetch = (async (input: RequestInfo | URL, init?: RequestInit) => {
    const requestUrl = input instanceof Request ? input.url : String(input);
    const url = new URL(requestUrl, window.location.origin);
    if (url.origin !== window.location.origin) return originalFetch(input, init);

    const token = currentAccessToken ?? await refreshToken();
    if (!token) return originalFetch(input, init);

    const headers = new Headers(input instanceof Request ? input.headers : undefined);
    if (init?.headers) new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    headers.set('x-supabase-access-token', token);

    if (input instanceof Request) {
      return originalFetch(new Request(input, { ...init, headers }));
    }
    return originalFetch(input, { ...init, headers });
  }) as typeof window.fetch;
}

installServerFunctionAuthTransport();
